include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    directives_ordering: ignore
    public_member_api_docs: ignore
    library_private_types_in_public_api: ignore
    depend_on_referenced_packages: ignore
    document_ignores: ignore
  exclude:
    - "**/*.g.dart"
