include: ../../analysis_options.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
    sort_unnamed_constructors_first: ignore
    avoid_private_typedef_functions: ignore
    unused_element: ignore
