targets:
  $default:
    builders:
      json_serializable:
        enabled: true
        generate_for:
          include:
            - lib/models/*.dart

        options:
          explicit_to_json: true
          include_if_null: false
          any_map: true

      copy_with_extension_gen:
        enabled: true
