name: domain
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  autoequal: ^0.8.0
  equatable: ^2.0.5

dev_dependencies:
  autoequal_gen: ^0.8.0
  build_runner: ^2.4.4
  mocktail: ^1.0.4
  test: ^1.26.2
  very_good_analysis: ^9.0.0

scripts: ../../derry.yaml
